"""migración inicial

Revision ID: eb55fcbe59e1
Revises: 
Create Date: 2025-04-25 11:16:21.143587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb55fcbe59e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_id'), 'training_sessions', ['id'], unique=False)
    op.create_table('exercises_performed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('id_training', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_training'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_performed_id'), 'exercises_performed', ['id'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('id_exercise', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_exercise'], ['exercises_performed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_id'), 'series', ['id'], unique=False)
    op.add_column('foods', sa.Column('fecha', sa.Date(), nullable=True))
    op.alter_column('foods', 'id_food',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('foods', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('foods', 'calorias',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('foods', 'carbohidratos',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('foods', 'proteinas',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('foods', 'grasas',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_foods_descripcion'), 'foods', ['descripcion'], unique=False)
    op.create_index(op.f('ix_foods_id_food'), 'foods', ['id_food'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.NUMERIC(precision=10),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=10),
               type_=sa.NUMERIC(precision=10),
               existing_nullable=True)
    op.drop_index(op.f('ix_foods_id_food'), table_name='foods')
    op.drop_index(op.f('ix_foods_descripcion'), table_name='foods')
    op.alter_column('foods', 'grasas',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('foods', 'proteinas',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('foods', 'carbohidratos',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('foods', 'calorias',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('foods', 'descripcion',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('foods', 'id_food',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('foods', 'fecha')
    op.drop_index(op.f('ix_series_id'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_exercises_performed_id'), table_name='exercises_performed')
    op.drop_table('exercises_performed')
    op.drop_index(op.f('ix_training_sessions_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    # ### end Alembic commands ###
