"""agregar usuario_id en historial

Revision ID: 3ce3a8127321
Revises: 637125e6e857
Create Date: 2025-04-27 15:43:27.724339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce3a8127321'
down_revision: Union[str, None] = '637125e6e857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historial', sa.Column('usuario_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historial', 'usuario_id')
    # ### end Alembic commands ###
