"""create tablas de nutrición

Revision ID: af94edf93557
Revises: 218c81c296db
Create Date: 2025-04-29 10:05:25.493070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af94edf93557'
down_revision: Union[str, None] = '218c81c296db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comidas_fecha'), 'comidas', ['fecha'], unique=False)
    op.create_index(op.f('ix_comidas_id'), 'comidas', ['id'], unique=False)
    op.create_index(op.f('ix_comidas_tipo'), 'comidas', ['tipo'], unique=False)
    op.create_table('registro_alimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gramos', sa.Float(), nullable=True),
    sa.Column('alimento_id', sa.Integer(), nullable=True),
    sa.Column('comida_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ),
    sa.ForeignKeyConstraint(['comida_id'], ['comidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_alimentos_id'), 'registro_alimentos', ['id'], unique=False)
    op.alter_column('historial', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historial', 'usuario_id',
    existing_type=sa.INTEGER(),
    nullable=True)
    op.drop_index(op.f('ix_registro_alimentos_id'), table_name='registro_alimentos')
    op.drop_table('registro_alimentos')
    op.drop_index(op.f('ix_comidas_tipo'), table_name='comidas')
    op.drop_index(op.f('ix_comidas_id'), table_name='comidas')
    op.drop_index(op.f('ix_comidas_fecha'), table_name='comidas')
    op.drop_table('comidas')
    # ### end Alembic commands ###
