"""crear tablas iniciales

Revision ID: ef992b835f65
Revises: 
Create Date: 2025-04-27 15:37:10.727542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef992b835f65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=True),
    sa.Column('fecha_realizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_id'), 'historial', ['id'], unique=False)
    op.drop_index('ix_entrenamientos_id', table_name='entrenamientos')
    op.drop_index('ix_entrenamientos_nombre', table_name='entrenamientos')
    op.drop_table('entrenamientos')
    op.drop_index('ix_alimentos_id', table_name='alimentos')
    op.drop_index('ix_alimentos_nombre', table_name='alimentos')
    op.drop_table('alimentos')
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.drop_index('ix_usuarios_id', table_name='usuarios')
    op.drop_index('ix_usuarios_username', table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usuarios_username', 'usuarios', ['username'], unique=1)
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False)
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=1)
    op.create_table('alimentos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=True),
    sa.Column('proteinas', sa.FLOAT(), nullable=True),
    sa.Column('carbohidratos', sa.FLOAT(), nullable=True),
    sa.Column('grasas', sa.FLOAT(), nullable=True),
    sa.Column('calorias', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alimentos_nombre', 'alimentos', ['nombre'], unique=False)
    op.create_index('ix_alimentos_id', 'alimentos', ['id'], unique=False)
    op.create_table('entrenamientos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=True),
    sa.Column('descripcion', sa.VARCHAR(), nullable=True),
    sa.Column('duracion_minutos', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entrenamientos_nombre', 'entrenamientos', ['nombre'], unique=False)
    op.create_index('ix_entrenamientos_id', 'entrenamientos', ['id'], unique=False)
    op.drop_index(op.f('ix_historial_id'), table_name='historial')
    op.drop_table('historial')
    # ### end Alembic commands ###
