"""initial

Revision ID: efec56382b82
Revises: 
Create Date: 2025-07-06 19:22:50.296718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efec56382b82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('proteinas', sa.Float(), nullable=True),
    sa.Column('carbohidratos', sa.Float(), nullable=True),
    sa.Column('grasas', sa.Float(), nullable=True),
    sa.Column('calorias', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alimentos_id'), 'alimentos', ['id'], unique=False)
    op.create_index(op.f('ix_alimentos_nombre'), 'alimentos', ['nombre'], unique=False)
    op.create_table('entrenamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrenamientos_id'), 'entrenamientos', ['id'], unique=False)
    op.create_index(op.f('ix_entrenamientos_nombre'), 'entrenamientos', ['nombre'], unique=False)
    op.create_table('objetivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objetivo_descripcion'), 'objetivo', ['descripcion'], unique=False)
    op.create_index(op.f('ix_objetivo_id'), 'objetivo', ['id'], unique=False)
    op.create_table('rutinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rutina', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutinas_id'), 'rutinas', ['id'], unique=False)
    op.create_index(op.f('ix_rutinas_nombre_rutina'), 'rutinas', ['nombre_rutina'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('comidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comidas_fecha'), 'comidas', ['fecha'], unique=False)
    op.create_index(op.f('ix_comidas_id'), 'comidas', ['id'], unique=False)
    op.create_index(op.f('ix_comidas_tipo'), 'comidas', ['tipo'], unique=False)
    op.create_table('ejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_ejercicio', sa.String(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('rutina_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ejercicios_id'), 'ejercicios', ['id'], unique=False)
    op.create_table('historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_realizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_id'), 'historial', ['id'], unique=False)
    op.create_table('medida_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('nombre_medida', sa.String(), nullable=True),
    sa.Column('unidad_medida', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medida_usuario_fecha'), 'medida_usuario', ['fecha'], unique=False)
    op.create_index(op.f('ix_medida_usuario_id'), 'medida_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_medida_usuario_nombre_medida'), 'medida_usuario', ['nombre_medida'], unique=False)
    op.create_index(op.f('ix_medida_usuario_unidad_medida'), 'medida_usuario', ['unidad_medida'], unique=False)
    op.create_index(op.f('ix_medida_usuario_valor'), 'medida_usuario', ['valor'], unique=False)
    op.create_table('objetivo_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peso_objetivo', sa.Float(), nullable=True),
    sa.Column('velocidad', sa.String(), nullable=True),
    sa.Column('id_objetivo', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_objetivo'], ['objetivo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfil_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('actividad', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_usuario_actividad'), 'perfil_usuario', ['actividad'], unique=False)
    op.create_index(op.f('ix_perfil_usuario_altura'), 'perfil_usuario', ['altura'], unique=False)
    op.create_index(op.f('ix_perfil_usuario_edad'), 'perfil_usuario', ['edad'], unique=False)
    op.create_index(op.f('ix_perfil_usuario_id'), 'perfil_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_perfil_usuario_peso'), 'perfil_usuario', ['peso'], unique=False)
    op.create_index(op.f('ix_perfil_usuario_sexo'), 'perfil_usuario', ['sexo'], unique=False)
    op.create_table('registro_alimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gramos', sa.Float(), nullable=True),
    sa.Column('alimento_id', sa.Integer(), nullable=True),
    sa.Column('comida_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ),
    sa.ForeignKeyConstraint(['comida_id'], ['comidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_alimentos_id'), 'registro_alimentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registro_alimentos_id'), table_name='registro_alimentos')
    op.drop_table('registro_alimentos')
    op.drop_index(op.f('ix_perfil_usuario_sexo'), table_name='perfil_usuario')
    op.drop_index(op.f('ix_perfil_usuario_peso'), table_name='perfil_usuario')
    op.drop_index(op.f('ix_perfil_usuario_id'), table_name='perfil_usuario')
    op.drop_index(op.f('ix_perfil_usuario_edad'), table_name='perfil_usuario')
    op.drop_index(op.f('ix_perfil_usuario_altura'), table_name='perfil_usuario')
    op.drop_index(op.f('ix_perfil_usuario_actividad'), table_name='perfil_usuario')
    op.drop_table('perfil_usuario')
    op.drop_table('objetivo_usuario')
    op.drop_index(op.f('ix_medida_usuario_valor'), table_name='medida_usuario')
    op.drop_index(op.f('ix_medida_usuario_unidad_medida'), table_name='medida_usuario')
    op.drop_index(op.f('ix_medida_usuario_nombre_medida'), table_name='medida_usuario')
    op.drop_index(op.f('ix_medida_usuario_id'), table_name='medida_usuario')
    op.drop_index(op.f('ix_medida_usuario_fecha'), table_name='medida_usuario')
    op.drop_table('medida_usuario')
    op.drop_index(op.f('ix_historial_id'), table_name='historial')
    op.drop_table('historial')
    op.drop_index(op.f('ix_ejercicios_id'), table_name='ejercicios')
    op.drop_table('ejercicios')
    op.drop_index(op.f('ix_comidas_tipo'), table_name='comidas')
    op.drop_index(op.f('ix_comidas_id'), table_name='comidas')
    op.drop_index(op.f('ix_comidas_fecha'), table_name='comidas')
    op.drop_table('comidas')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_rutinas_nombre_rutina'), table_name='rutinas')
    op.drop_index(op.f('ix_rutinas_id'), table_name='rutinas')
    op.drop_table('rutinas')
    op.drop_index(op.f('ix_objetivo_id'), table_name='objetivo')
    op.drop_index(op.f('ix_objetivo_descripcion'), table_name='objetivo')
    op.drop_table('objetivo')
    op.drop_index(op.f('ix_entrenamientos_nombre'), table_name='entrenamientos')
    op.drop_index(op.f('ix_entrenamientos_id'), table_name='entrenamientos')
    op.drop_table('entrenamientos')
    op.drop_index(op.f('ix_alimentos_nombre'), table_name='alimentos')
    op.drop_index(op.f('ix_alimentos_id'), table_name='alimentos')
    op.drop_table('alimentos')
    # ### end Alembic commands ###
